name: udemy_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  http: ^0.13.4
  flutter_svg:
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.2.0
  location: ^4.4.0
  latlng: ^0.2.0
  syncfusion_flutter_maps: ^20.2.48
  internet_connection_checker: ^0.0.1+4
  url_launcher: ^6.1.6
  flutter_phone_direct_caller: ^2.1.1
  intl: ^0.17.0
  geolocator: ^9.0.2
  flutter_rounded_date_picker: 3.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  restart_app: ^1.1.0
  flutter_phoenix: ^1.1.0
  permission_handler: ^10.2.0
  flutter_downloader: ^1.10.2
  path:
  flutter_time_picker_spinner:
  sizer: ^2.0.15
#  path_provider_android:
  path_provider:
  media_scanner: ^2.1.0
  gallery_saver: ^2.3.2
  open_file: ^3.2.1
  file_picker:
  device_info_plus:
  external_path: ^1.0.3
  dotted_border:
  flutter_html:
  flutter_animated_dialog: ^2.0.1
#  flutter_svg_provider: ^1.0.3



  firebase_core: ^2.2.0
#  flutter_local_notifications: ^12.0.3
#  firebase_core_platform_interface: 4.5.2
#  firebase_crashlytics: ^3.0.3
  firebase_database: ^10.0.4
#  firebase_auth: ^4.1.1
#  firebase_messaging: ^14.0.1
  firebase_messaging: ^14.0.1
  native_notify: ^0.0.3
  flutter_webview_pro: ^3.0.1+4
  google_fonts: ^2.3.1
  dropdown_button2: ^1.9.3
  fdottedline_nullsafety: ^2.0.1
  lottie:
  flutter_holo_date_picker: ^1.1.0
  proste_bezier_curve: ^2.0.2
  flutter_custom_clippers: ^2.1.0
  syncfusion_flutter_calendar: ^20.4.54
  intro_views_flutter: ^3.2.0
  flutter_dash: ^1.0.0
  flutter_switch: ^0.3.2
  visibility_detector: ^0.4.0+2
  upgrader: ^4.6.1
  percent_indicator: ^4.0.1
  syncfusion_flutter_gauges:
#  nfc_manager:

#  downloads_path_provider_28: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "images/playstore12.png"
  theme_color: "#FAFAFA"
  background_color:  "#FAFAFA"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/lang/
    - assets/lang/trackwarelogo.json
    - assets/lang/school_bus.json
    - assets/lang/animation_lkz4jtzc.json
    - images/new_splash_background.png
    - images/ic_new_logo.png
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/lang/anm.json
    - assets/lang/high.json
    - assets/lang/like.json
    - images/img_circle.png
    - images/img_error.png
    - images/img_absent.png
    - images/icon_ab.png
    - images/clinic.svg
    - images/clinic_icon.svg
    - images/rounded.svg
    - images/chevron_left_solid.svg
    - images/no_absence_added.jpeg
    - images/edit_solid.svg
    - images/filter_solid.svg
    - images/award_solid.svg
    - images/Image321_11zon.png
    - images/times_solid.svg
    - images/table_solid.svg
    - images/thermometer_quarter_solid.svg
    - images/absent.png
    - images/late.png
    - images/pencil_alt_solid_wor.svg
    - images/thumbtack_solid.svg
    - images/cloud_upload_alt_solid.svg
    - images/pdf.svg
    - images/calendar_day_solid.svg
    - images/worksheets.png
    - images/school_Monochromatic.png
    - images/assigments.png
    - images/calendar_Monochromatic.png
    - images/decline.png
    - images/grades_pana.png
    - images/trackware_school.png
    - images/bus.svg
    - images/icons8_megaphone.svg
    - images/icons8_open_book.svg
    - images/icons8_note.svg
    - images/icon_feather_search.svg
    - images/icons8_home6.svg
    - images/icons8_four_squares.svg
    - images/filter11.svg
    - images/icons8_open_book3.svg
    - images/icons8_note2.svg
    - images/icons8_megaphone_1.svg
    - images/bus_1.svg
    - images/calendar_11.svg
    - images/icons8_four_squares_full.svg
    - images/absence_new.svg
    - images/new_login.png
    - images/icons8_secure.svg
    - images/icons8_school_building.svg
    - images/icons8_english_to_arabic.svg
    - images/home_50.png
    - images/icons8_fire_exit.svg
    - images/icons8_comments.svg
    - images/new_bus.svg
    - images/students.svg
    - images/ecanteen.svg
    - images/new_app_cart.svg
    - images/cube_geometry_shape_figure_form_icon.svg
    - images/logo_without.png
    - images/logo_trackware_with.svg
    - images/bus_genr.png
    - images/cart.png
    - images/casual_life_3d_reward_badge_with_star_and_ribbon.png
    - images/casual_life_3d_gold_trophy_1.png



#    - assets/lang

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Nunito
       fonts:
         - asset: assets/Nunito-VariableFont_wght.ttf
         - asset: assets/Nunito-Italic-VariableFont_wght.ttf
           style: italic
#           weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
#           weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
